# Generated by Django 6.0.2 on 2026-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pspoutboxentry',
            new_name='psp_outbox_status_346ee3_idx',
            old_name='psp_outbox_status_5b4f31_idx',
        ),
        migrations.AlterField(
            model_name='pspoutboxentry',
            name='kind',
            field=models.CharField(choices=[('mo_session', 'MO session'), ('workstation_session', 'Workstation session (off-MO)'), ('reputation_event', 'Reputation event'), ('form_submission', 'Form submission')], db_index=True, max_length=32),
        ),
    ]
