# Generated by Django 6.0.2 on 2026-03-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='worker',
        ),
        migrations.CreateModel(
            name='SessionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_workers', to='work_sessions.worksession')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_sessions', to='workers.worker')),
            ],
            options={
                'db_table': 'session_workers',
                'unique_together': {('session', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='worksession',
            name='workers',
            field=models.ManyToManyField(related_name='work_sessions', through='work_sessions.SessionWorker', to='workers.worker'),
        ),
    ]
