# Generated by Django 6.0.2 on 2026-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0002_remove_worksession_worker_sessionworker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='performance_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
