# Generated by Django 6.0.2 on 2026-03-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('work_sessions', '0003_worksession_performance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='items.item'),
        ),
    ]
