# Generated by Django 6.0.2 on 2026-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0004_worksession_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='quantity_rejected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('verified', 'Verified')], default='completed', max_length=20),
        ),
    ]
