# Generated by Django 6.0.2 on 2026-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0005_worksession_quantity_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='override_target_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='override_target_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='override_task_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
