# Generated by Django 6.0.2 on 2026-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
