# Generated by Django 6.0.2 on 2026-03-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_qa',
            field=models.BooleanField(default=False),
        ),
    ]
