# Generated by Django 6.0.2 on 2026-04-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0006_worksession_override_target_duration_and_more'),
        ('workers', '0003_worker_is_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='reputation_score',
            field=models.IntegerField(default=650),
        ),
        migrations.CreateModel(
            name='WorkerReputationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auto_perf_excellent', 'Performance >=125%'), ('auto_perf_high', 'Performance 100-124%'), ('auto_perf_low', 'Performance 50-74%'), ('auto_perf_very_low', 'Performance <50%'), ('manual_positive', 'Positive QC feedback'), ('manual_negative', 'Negative QC feedback')], max_length=32)),
                ('score_delta', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to='workers.worker')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_events', to='work_sessions.worksession')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_events', to='workers.worker')),
            ],
            options={
                'db_table': 'worker_reputation_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
