# Generated by Django 6.0.2 on 2026-08-04 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_personalkiosktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalKioskAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='workers.personalkiosktoken')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_kiosk_sessions', to='workers.worker')),
            ],
            options={
                'db_table': 'personal_kiosk_auth_sessions',
                'indexes': [models.Index(fields=['worker', 'revoked_at'], name='personal_ki_worker__767d34_idx'), models.Index(fields=['expires_at'], name='personal_ki_expires_92c54f_idx')],
            },
        ),
    ]
