# Generated by Django 6.0.2 on 2026-03-15 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_sessions', '0005_worksession_quantity_rejected_and_more'),
        ('workstations', '0004_sop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('start', 'Session Start'), ('end', 'Session End'), ('both', 'Both')], default='start', max_length=10)),
                ('schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_forms', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_forms', to='workstations.workstation')),
            ],
            options={
                'db_table': 'dynamic_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dynamic_forms.dynamicform')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='work_sessions.worksession')),
            ],
            options={
                'db_table': 'form_responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
