export const API_CONFIG = {
  baseUrl: process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000",
  wsBase: process.env.NEXT_PUBLIC_WS_URL || "ws://localhost:8000",
  endpoints: {
    auth: {
      register: "/api/accounts/register",
      login: "/api/accounts/login",
      logout: "/api/accounts/logout",
      refresh: "/api/accounts/refresh",
      user: "/api/accounts/user",
      passwordReset: "/api/accounts/password-reset/",
      passwordResetConfirm: "/api/accounts/password-reset/confirm/",
    },
    settings: {
      base: "/api/settings/",
    },
    meta: {
      currencies: "/api/meta/currencies/",
      languages: "/api/meta/languages/",
      timezones: "/api/meta/timezones/",
    },
    workstations: {
      base: "/api/workstations/",
      detail: (id: number) => `/api/workstations/${id}/`,
      sop: (id: number) => `/api/workstations/${id}/sop/`,
    },
    workers: {
      base: "/api/workers/",
      detail: (id: number) => `/api/workers/${id}/`,
      groups: "/api/workers/groups/",
      groupDetail: (id: number) => `/api/workers/groups/${id}/`,
      leaderboard: '/api/workers/leaderboard/',
      reputationEvents: "/api/workers/reputation/events/",
    },
    sessions: {
      base: "/api/sessions/",
      detail: (id: number) => `/api/sessions/${id}/`,
      start: "/api/sessions/start/",
      stop: (id: number) => `/api/sessions/${id}/stop/`,
      active: "/api/sessions/active/",
    },
    dashboard: {
        overview: "/api/dashboard/overview/",
        wsToken: "/api/dashboard/ws-token/",
        ws: "/ws/dashboard/",
        workerStats: (id: number) => `/api/dashboard/workers/${id}/stats/`,
    },
    items: {
        base: "/api/items/",
        detail: (id: number) => `/api/items/${id}/`,
        search: "/api/items/search/",
    },
    kiosk: {
        base: (token: string) => `/api/kiosk/${token}/`,
        workers: (token: string) => `/api/kiosk/${token}/workers/`,
        verifyPin: (token: string) => `/api/kiosk/${token}/verify-pin/`,
        start: (token: string) => `/api/kiosk/${token}/start/`,
        active: (token: string) => `/api/kiosk/${token}/active/`,
        stop: (token: string) => `/api/kiosk/${token}/stop/`,
        searchItems: (token: string) => `/api/kiosk/${token}/items/`,
        sop: (token: string) => `/api/kiosk/${token}/sop/`,
        forms: (token: string, trigger: string) => `/api/kiosk/${token}/forms/?trigger=${trigger}`,
        formRespond: (token: string, formId: number) => `/api/kiosk/${token}/forms/${formId}/respond/`,
        qcWorkers: (token: string) => `/api/kiosk/${token}/qc-workers/`,
    },
    qc: {
        token: "/api/qc/token/",
        workers: (token: string) => `/api/qc/${token}/workers/`,
        allWorkers: (token: string) => `/api/qc/${token}/all-workers/`,
        verifyPin: (token: string) => `/api/qc/${token}/verify-pin/`,
        workstations: (token: string) => `/api/qc/${token}/workstations/`,
        sessions: (token: string) => `/api/qc/${token}/sessions/`,
        verifySession: (token: string, sessionId: number) => `/api/qc/${token}/sessions/${sessionId}/verify/`,
        feedback: (token: string) => `/api/qc/${token}/feedback/`,
    },
    subscription: {
        base: "/api/subscription/",
    },
    dynamicForms: {
        base: "/api/dynamic-forms/",
        detail: (id: number) => `/api/dynamic-forms/${id}/`,
        sessionResponses: (sessionId: number) => `/api/dynamic-forms/sessions/${sessionId}/responses/`,
    },
  },
} as const;