# Generated by Django 6.0.2 on 2026-02-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12h'), ('24h', '24h')], default='24h', max_length=5)),
                ('timezone', models.CharField(default='Europe/London', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('decimal_separator', models.CharField(choices=[('.', 'Period (1,000.00)'), (',', 'Comma (1.000,00)')], default='.', max_length=1)),
                ('thousands_separator', models.CharField(choices=[(',', 'Comma (1,000.00)'), ('.', 'Period (1.000,00)'), (' ', 'Space (1 000,00)')], default=',', max_length=1)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('working_days_per_week', models.IntegerField(default=5)),
                ('overtime_threshold', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('week_starts_on', models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
