# Generated by Django 6.0.2 on 2026-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='work_start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
