# Generated by Django 6.0.2 on 2026-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_usersettings_work_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='eng', max_length=10),
        ),
    ]
