# Generated by Django 6.0.2 on 2026-09-17 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
        ('workers', '0010_personalkioskauthsession'),
        ('workstations', '0009_cleaning_schedule_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mo_uuid', models.CharField(db_index=True, max_length=64)),
                ('mo_step_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_notes_authored', to='workers.worker')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_notes', to='workstations.workstation')),
            ],
            options={
                'db_table': 'qc_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mo_uuid', '-created_at'], name='qc_notes_mo_idx')],
            },
        ),
    ]
