# Generated by Django 6.0.2 on 2026-03-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_hours_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overtime_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overtime_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('week_starts_on', models.CharField(blank=True, choices=[('monday', 'Monday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workstations',
                'ordering': ['-created_at'],
            },
        ),
    ]
