# Generated by Django 6.0.2 on 2026-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='target_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='target_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
