# Generated by Django 6.0.2 on 2026-03-07 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0002_workstation_target_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='kiosk_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
