# Generated by Django 6.0.2 on 2026-03-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0003_workstation_kiosk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workstation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sop', to='workstations.workstation')),
            ],
            options={
                'db_table': 'sops',
            },
        ),
    ]
