# Generated by Django 6.0.2 on 2026-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0004_sop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
