# Generated by Django 6.0.2 on 2026-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0005_workstation_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
