# Generated by Django 6.0.2 on 2026-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0006_workstation_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='performance_formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
